[tool.towncrier]
    template = ".towncrier-template.rst"
    underlines = ["~"]
    title_format = "{version}"
    issue_format = "`#{issue} <https://github.com/oca/oca-github-bot/issues/{issue}>`_"
    directory = "newsfragments/"
    filename = "HISTORY.rst"

[tool.pip-deepfreeze.sync]
extras = "test"
